fail_fast: true
default_language_version:
  python: python3
repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: detect-private-key

  - repo: local
    hooks:
      - id: isort
        name: isort-local
        entry: python -m isort
        language: system
        types: [python]
        pass_filenames: true
      - id: black
        name: black-local
        entry: python -m black --config .black.toml
        language: system
        types: [python]
        pass_filenames: true
      - id: bandit
        name: bandit-local
        entry: python -m bandit -c .bandit.yaml -r
        language: system
        types: [python]
        pass_filenames: true
      - id: mypy
        name: mypy-local
        entry: python -m mypy --config-file=.mypy.ini .
        language: system
        types: [python]
        pass_filenames: false
      - id: prospector
        name: prospector-local
        entry: python -m prospector --messages-only
        language: system
        types: [python]
        pass_filenames: true
