API_URL = "https://aoe2.net/api"

# player constants
COLORS = {
    1: "blue",
    2: "red",
    3: "green",
    4: "yellow",
    5: "teal",
    6: "purple",
    7: "gray",
    8: "orange",
}
CIVILIZATIONS = {
    0: "Aztecs",
    1: "Berbers",
    2: "Britons",
    3: "Bulgarians",
    4: "Burmese",
    5: "Byzantines",
    6: "Celts",
    7: "Chinese",
    8: "Cumans",
    9: "Ethiopians",
    10: "Franks",
    11: "Goths",
    12: "Huns",
    13: "Incas",
    14: "Indians",
    15: "Italians",
    16: "Japanese",
    17: "Khmer",
    18: "Koreans",
    19: "Lithuanians",
    20: "Magyars",
    21: "Malay",
    22: "Malians",
    23: "Mayans",
    24: "Mongols",
    25: "Persians",
    26: "Portuguese",
    27: "Saracens",
    28: "Slavs",
    29: "Spanish",
    30: "Tatars",
    31: "Teutons",
    32: "Turks",
    33: "Vietnamese",
    34: "Vikings",
}

# match constants
AGES = {
    0: "Standard",
    2: "Dark Age",
    3: "Feudal Age",
    4: "Castle Age",
    5: "Imperial Age",
    6: "Post-Imperial Age",
}
GAME_TYPES = {
    0: "Random Map",
    1: "Regicide",
    2: "Death Match",
    3: "Scenario",
    6: "King of the Hill",
    7: "Wonder Race",
    8: "Defend the Wonder",
    9: "Turbo Random Map",
    10: "Capture the Relic",
    11: "Sudden Death",
    13: "Empire Wars",
}
LEADERBOARD_TYPES = {
    0: "Unranked",
    1: "1v1 Death Match",
    2: "Team Death Match",
    3: "1v1 Random Map",
    4: "Team Random Map",
}
MAP_SIZES = {
    0: "Tiny (2 player)",
    1: "Small (3 player)",
    2: "Medium (4 player)",
    3: "Normal (6 player)",
    4: "Large (8 player)",
    5: "Giant",
    6: "Ludicrous",
}
MAP_TYPES = {
    9: "Arabia",
    10: "Archipelago",
    11: "Baltic",
    12: "Black Forest",
    13: "Coastal",
    14: "Continental",
    15: "Crater Lake",
    16: "Fortress",
    17: "Gold Rush",
    18: "Highland",
    19: "Islands",
    20: "Mediterranean",
    21: "Migration",
    22: "Rivers",
    23: "Team Islands",
    24: "Full Random",
    25: "Scandinavia",
    26: "Mongolia",
    27: "Yucatan",
    28: "Salt Marsh",
    29: "Arena",
    31: "Oasis",
    32: "Ghost Lake",
    33: "Nomad",
    49: "Iberia",
    50: "Britain",
    51: "Mideast",
    52: "Texas",
    53: "Italy",
    54: "Central America",
    55: "France",
    56: "Norse Lands",
    57: "Sea of Japan (East Sea)",
    58: "Byzantium",
    59: "Custom",
    60: "Random Land Map",
    62: "Random Real World Map",
    63: "Blind Random",
    65: "Random Special Map",
    66: "Random Special Map",
    67: "Acropolis",
    68: "Budapest",
    69: "Cenotes",
    70: "City of Lakes",
    71: "Golden Pit",
    72: "Hideout",
    73: "Hill Fort",
    74: "Lombardia",
    75: "Steppe",
    76: "Valley",
    77: "MegaRandom",
    78: "Hamburger",
    79: "CtR Random",
    80: "CtR Monsoon",
    81: "CtR Pyramid Descent",
    82: "CtR Spiral",
    83: "Kilimanjaro",
    84: "Mountain Pass",
    85: "Nile Delta",
    86: "Serengeti",
    87: "Socotra",
    88: "Amazon",
    89: "China",
    90: "Horn of Africa",
    91: "India",
    92: "Madagascar",
    93: "West Africa",
    94: "Bohemia",
    95: "Earth",
    96: "Canyons",
    97: "Enemy Archipelago",
    98: "Enemy Islands",
    99: "Far Out",
    100: "Front Line",
    101: "Inner Circle",
    102: "Motherland",
    103: "Open Plains",
    104: "Ring of Water",
    105: "Snakepit",
    106: "The Eye",
    107: "Australia",
    108: "Indochina",
    109: "Indonesia",
    110: "Strait of Malacca",
    111: "Philippines",
    112: "Bog Islands",
    113: "Mangrove Jungle",
    114: "Pacific Islands",
    115: "Sandbank",
    116: "Water Nomad",
    117: "Jungle Islands",
    118: "Holy Line",
    119: "Border Stones",
    120: "Yin Yang",
    121: "Jungle Lanes",
    122: "Alpine Lakes",
    123: "Bogland",
    124: "Mountain Ridge",
    125: "Ravines",
    126: "Wolf Hill",
    132: "Antarctica",
    137: "Custom Map Pool",
    139: "Golden Swamp",
    140: "Four Lakes",
    141: "Land Nomad",
}
RATING_TYPES = {
    0: "Unranked",
    1: "1v1 Death Match",
    2: "1v1 Random Map",
    3: "Team Death Match",
    4: "Team Random Map",
}
RESOURCES = {
    0: "Standard",
    1: "Low",
    2: "Medium",
    3: "High",
    4: "Ultra High",
    5: "Infinite",
    6: "Random",
}
SPEEDS = {0: "Slow", 1: "Casual", 2: "Normal", 3: "Fast"}
VICTORY_TYPES = {1: "Conquest", 7: "Time Limit", 8: "Score", 9: "Standard", 11: "Last Man Standing"}
VISIBILITIES = {0: "Normal", 1: "Explored", 2: "All Visible"}
